import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import generator from "generate-password";

const Home: NextPage = () => {
  const generateUsername = () => {
    const username = generator.generate({
      length: 8,
      numbers: true,
      uppercase: false,
      excludeSimilarCharacters: true,
      strict: true,
    });

    console.log(username);
  };

  const generatePassword = () => {
    const password = generator.generate({
      length: 16,
      numbers: true,
      symbols: true,
      excludeSimilarCharacters: true,
      strict: true,
    });

    console.log(password);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={generateUsername}>Generate Username</button>

      <button onClick={generatePassword}>Generate Password</button>
    </div>
  );
};

export default Home;
